# Generated by Django 4.2.4 on 2023-09-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyinfo', '0005_room_participants_alter_message_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
